export const companies = [
    { 'name': 'google', 'link': 'https://i.imgur.com/ThsY7lh.png'},
    { 'name': 'amazon', 'link':'https://i.imgur.com/nLhGJnX.png' },
    { 'name': 'apple', 'link': 'https://i.imgur.com/uyeAT9N.png' },
    { 'name': 'microsoft', 'link': 'https://i.imgur.com/JT0bbQU.jpg'},
    { 'name': 'docusign', 'link': 'https://i.imgur.com/pW0elkG.jpg'},
    { 'name': 'tesla', 'link': 'https://i.imgur.com/j3e5pX6.png'},
    { 'name': 'genentech', 'link':'https://i.imgur.com/mhDnblJ.png' },
    { 'name': 'pinterest', 'link': 'https://i.imgur.com/1kGGxrD.png'},
    { 'name': 'ebay', 'link': 'https://i.imgur.com/hBNcnSO.png'},
    { 'name': 'instacart', 'link': 'https://i.imgur.com/COJ9G7G.jpg'},
    { 'name': 'nasa', 'link': 'https://i.imgur.com/glaIGF9.png'},
    { 'name': 'workday', 'link': 'https://i.imgur.com/lZl9DN8.png'},
    { 'name': 'chevron', 'link': 'https://i.imgur.com/UkakpVF.png' },
    { 'name': 'wells-fargo', 'link': 'https://i.imgur.com/Sb1Vxa3.png'},
    { 'name': 'hpe', 'link': 'https://i.imgur.com/ambn4aY.png'},
    { 'name': 'ibm', 'link': 'https://i.imgur.com/fttPjNT.png'},
    { 'name': 'intel', 'link': 'https://i.imgur.com/C6M4fox.png'},
    { 'name': 'keysight', 'link': 'https://i.imgur.com/LYYQbhB.png'},
    { 'name': 'texas-instruments', 'link': 'https://i.imgur.com/7ZrWuqp.png'},
    { 'name': 'varian', 'link': 'https://i.imgur.com/zLv3eJd.png'},
]