export const actives = [
    {
        name: 'ama2',
        year: 'Class of 2023',
        major: 'Podiatric Medicine and Engineering',
        cohort: 'Fall 2021 Cohort',
        position: 'President',
        linkedin: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
        image: '/officers/ama2.jpg',
    },
    {
        name: '💀',
        year: 'Class of 2023',
        major: 'Podiatric Medicine and Engineering',
        cohort: 'Fall 2021 Cohort',
        position: 'President',
        linkedin: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
        image: '/officers/laur2.jpg',
    },
    {
        name: 'daphers',
        year: 'Class of 2023',
        major: 'Podiatric Medicine and Engineering',
        cohort: 'Fall 2021 Cohort',
        position: 'President',
        linkedin: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
        image: '/officers/dap.jpg',
    },
    {
        name: 'mamanda2',
        year: 'Class of 2023',
        major: 'Podiatric Medicine and Engineering',
        cohort: 'Fall 2021 Cohort',
        position: 'President',
        linkedin: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
        image: '/officers/ama2.png',
    },
    {
        name: 'LOGEEZY2',
        year: 'Class of 2023',
        major: 'Podiatric Medicine and Engineering',
        cohort: 'Fall 2021 Cohort',
        position: 'President',
        linkedin: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
        image: '/officers/la3.jpeg',
    },
    {
        name: 'LOGEEZY',
        year: 'Class of 2023',
        major: 'Podiatric Medicine and Engineering',
        cohort: 'Fall 2021 Cohort',
        position: 'President',
        linkedin: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
        image: '/officers/laur.jpg',
    },
    {
        name: 'ken (bro is majestic)',
        year: 'Class of 2023',
        major: 'Podiatric Medicine and Engineering',
        cohort: 'Fall 2021 Cohort',
        position: 'President',
        linkedin: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
        image: '/officers/ken.png',
    },
    {
        name: '123jarebear123',
        year: 'Class of 2023',
        major: 'Podiatric Medicine and Engineering',
        cohort: 'Fall 2021 Cohort',
        position: 'President',
        linkedin: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
        image: '/officers/jarebear.jpg',
    },
    {
        name: 'spherical objects in mouth',
        year: 'Class of 2023',
        major: 'Podiatric Medicine and Engineering',
        cohort: 'Fall 2021 Cohort',
        position: 'President',
        linkedin: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
        image: '/officers/just.jpeg',
    },
    {
        name: 'n8 dogg',
        year: 'Class of 2023',
        major: 'Podiatric Medicine and Engineering',
        cohort: 'Fall 2021 Cohort',
        position: 'President',
        linkedin: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
        image: '/officers/n8.jpeg',
    },
    {
        name: 'thunderstorm',
        year: 'Class of 2023',
        major: 'Podiatric Medicine and Engineering',
        cohort: 'Fall 2021 Cohort',
        position: 'President',
        linkedin: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
        image: '/officers/aru.png',
    },
    {
        name: 'we ❤️ bananas',
        year: 'Class of 2023',
        major: 'Podiatric Medicine and Engineering',
        cohort: 'Fall 2021 Cohort',
        position: 'President',
        linkedin: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
        image: '/officers/ma.png',
    },
    
    {
        name: 'a brush a day keeps the dentist away',
        year: 'Class of 2023',
        major: 'Podiatric Medicine and Engineering',
        cohort: 'Fall 2021 Cohort',
        position: 'President',
        linkedin: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
        image: '/officers/ma2.jpeg',
    },
    {
        name: 'daphers2',
        year: 'Class of 2023',
        major: 'Podiatric Medicine and Engineering',
        cohort: 'Fall 2021 Cohort',
        position: 'President',
        linkedin: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
        image: '/officers/dap2.png',
    },

]