/*

----------- DATAactives.js
This is the active officer data for the Active Officers panel in the OFFICERS page.

********* It exports an array of JSON object constants. ************

Each JSON object has the format:

{
    name: 'Officer Name',
    year: 'Class of []',
    major: '[INSERT MAJOR HERE]',
    cohort: '[TERM] [YEAR] Cohort',
    position: 'President',
    linkedin: 'https://linkedin.com/[officer]',
    image: '/officers/[officer-photo].jpg',
}

******* Each json must follow the above format. If any properties are in a different order as listed above or
even missing, the program will likely crash. *************

This entire project imports all photos from the 'public' directory. 
The path prefix '/' is already set to already reference this folder.
So, if the file 'image1.png' is in the 'folder1' directory in the 'public' directory, reference this file with the file path:
    '/folder1/image1.png'. DO NOT USE THE PATH '/public/folder1/image1.png', IT WILL NOT WORK IF YOU DO SO.
Having '/' be the prefix for the path is already recognized as referencing the 'public' directory.

THIS component will pull images from the directory '/officers' in the 'public' directory.
When updating the photos, add your desired photo in this directory, and update the
exported JSONs with the appropriate image paths and descriptions. The path should be '/officers/[logo-file].png'.

**** Executive board and active officer photos will be in the same directory, the '/officers' directory. ****

The order which you list the officers here is there order they will be displayed
on the webpage.

*/

export const allofficers = [
    {
        name: 'Lauren Gee',
        year: 'Class of 2024',
        major: 'Mechanical Engineering',
        cohort: 'Fall 2022 Cohort',
        position: 'Internal Affairs',
        linkedin: 'https://www.linkedin.com/in/lauren-gee/',
        image: '/officers/lauren.JPG',
    },
    {
        name: 'Richmond Ballesteros',
        year: 'Class of 2023',
        major: 'Computer Science',
        cohort: 'Fall 2022 Cohort',
        position: 'Internal Affairs',
        linkedin: 'https://www.linkedin.com/in/richmond-ballesteros-56aa99210/',
        image: '/officers/ballesteros-richmond.JPEG',
    },
        {
        name: 'Abubakr Hadwan',
        year: 'Class of 2024',
        major: 'Biomedical Engineering',
        cohort: 'Fall 2022 Cohort',
        position: 'Internal Affairs',
        linkedin: 'https://www.linkedin.com/in/abubakr-hadwan/',
        image: '/officers/hadwan_abubakr.JPG',
    },
    {
        name: 'Matthew Suyetani',
        year: 'Class of 2024',
        major: 'Mechanical Engineering',
        cohort: 'Fall 2022 Cohort',
        position: 'Career Development',
        linkedin: 'https://www.linkedin.com/in/matthewsuyetani/',
        image: '/officers/Suyetani_Matthew.JPG',
    },
    {
        name: 'Kenneth Bui',
        year: 'Class of 2024',
        major: 'Biomedical Engineering',
        cohort: 'Founding Cohort',
        position: 'Committee Director, Finance',
        linkedin: '',
        image: '/officers/Bui_Kenneth.JPG',
    },
    {
        name: 'Daphne Lee',
        year: 'Class of 2024',
        major: 'Biological Systems Engineering',
        cohort: 'Founding Cohort',
        position: 'Internal Affairs',
        linkedin: 'https://www.linkedin.com/in/daphnelee123/',
        image: '/officers/daphne.JPG',
    },
    {
        name: 'Adit Jain',
        year: 'Class of 2024',
        major: 'Biomedical Engineering',
        cohort: 'Founding Cohort',
        position: 'Committee Director, Professional Relations',
        linkedin: 'https://www.linkedin.com/in/aditjain125/',
        image: '/officers/Jain_Adit.jpg',
    },
    {
        name: 'Riya Prashad',
        year: 'Class of 2024',
        major: 'Biomedical Engineering',
        cohort: 'Founding Cohort',
        position: 'Internal Affairs',
        linkedin: 'https://www.linkedin.com/in/riya-prashad-06bb74187/',
        image: '/officers/Prashad_Riya.png',
    },
    {
        name: 'Calvin Chen',
        year: 'Class of 2024',
        major: 'Computer Science',
        cohort: 'Founding Cohort',
        position: 'Committee Director, Career Development',
        linkedin: 'https://www.linkedin.com/in/calvinchenn/',
        image: '/officers/Chen_Calvin.jpg',
    },
    {
        name: 'Xiaolin Ma',
        year: 'Class of 2024',
        major: 'Computer Science',
        cohort: 'Founding Cohort',
        position: 'Committee Director, Marketing',
        linkedin: 'https://www.linkedin.com/in/calvinchenn/',
        image: '/officers/Ma_Xiaolin.jpg',
    },
    {
        name: 'Christopher Lo',
        year: 'Class of 2025',
        major: 'Computer Science',
        cohort: 'Spring 2023 Cohort',
        position: 'Program Manager',
        linkedin: 'https://www.linkedin.com/in/christopherlo34/',
        image: '/officers/Lo_Chris.jpg',
    },
    {
        name: 'Matthew Wang',
        year: 'Class of 2025',
        major: 'Business Economics and Technology Management',
        cohort: 'Spring 2023 Cohort',
        position: 'Program Manager',
        linkedin: 'https://www.linkedin.com/in/-matthew-wang-/',
        image: '/officers/Wang_Matthew.jpg',
    },
    {
        name: 'Taylor Chin',
        year: 'Class of 2026',
        major: 'Mechanical Engineering',
        cohort: 'Spring 2023 Cohort',
        position: 'Professional Relations',
        linkedin: 'https://www.linkedin.com/in/taylorchin2/',
        image: '/officers/Chin_Taylor.jpeg',
    },
    {
        name: 'Greg Chang',
        year: 'Class of 2025',
        major: 'Computer Science',
        cohort: 'Spring 2023 Cohort',
        position: 'Professional Relations',
        linkedin: 'https://www.linkedin.com/in/gregjchang/',
        image: '/officers/Chang_Greg.jpg',
    },
    {
        name: 'Daniel Petroski',
        year: 'Class of 2024',
        major: 'Civil Engineering',
        cohort: 'Spring 2023 Cohort',
        position: 'Professional Relations',
        linkedin: 'https://www.linkedin.com/in/daniel-petroski/',
        image: '/officers/Petroski_Daniel.jpg',
    },
    {
        name: 'Cory Cadavona',
        year: 'Class of 2025',
        major: 'Computer Engineering',
        cohort: 'Spring 2023 Cohort',
        position: 'Professional Relations',
        linkedin: 'https://www.linkedin.com/in/corycadavona/',
        image: '/officers/Cadavona_Cory.jpg',
    },
    {
        name: 'Justin Kwong',
        year: 'Class of 2025',
        major: 'Mechanical Engineering',
        cohort: 'Spring 2023 Cohort',
        position: 'Professional Relations',
        linkedin: 'https://www.linkedin.com/in/justin-kwong-4855b7242/',
        image: '/officers/Kwong_Justin.jpeg',
    },
    {
        name: 'Natalie Kuang',
        year: 'Class of 2025',
        major: 'Biomedical Engineering',
        cohort: 'Spring 2023 Cohort',
        position: 'Career Development',
        linkedin: 'https://www.linkedin.com/in/natalie-kuang-ucd2025/',
        image: '/officers/Kuang_Natalie.JPG',
    },
    {
        name: 'Kaitlyn Tran',
        year: 'Class of 2024',
        major: 'Civil Engineering',
        cohort: 'Spring 2023 Cohort',
        position: 'Career Development',
        linkedin: 'https://www.linkedin.com/in/kaitlyn-tran-111966174/',
        image: '/officers/Tran_Kaitlyn.png',
    },
    {
        name: 'Josh Lopez',
        year: 'Class of 2023',
        major: 'Biomedical Engineering',
        cohort: 'Spring 2023 Cohort',
        position: 'Career Development',
        linkedin: 'https://www.linkedin.com/in/jnlope/',
        image: '/officers/Lopez_Josh.jpeg',
    },
    {
        name: 'Keshav Lodha',
        year: 'Class of 2025',
        major: 'Computer Science and Statistics',
        cohort: 'Spring 2023 Cohort',
        position: 'Finance',
        linkedin: 'https://www.linkedin.com/in/keshav-lodha-0497541b7/',
        image: '/officers/Lodha_Keshav.png',
    },
    {
        name: 'Newland Luu',
        year: 'Class of 2024',
        major: 'Computer Science',
        cohort: 'Spring 2023 Cohort',
        position: 'Internal Affairs',
        linkedin: 'https://www.linkedin.com/in/newland-luu-512805210/',
        image: '/officers/Luu_Newland.jpg',
    },
    {
        name: 'Bryan Nguyen',
        year: 'Class of 2026',
        major: 'Mechanical Engineering',
        cohort: 'Spring 2023 Cohort',
        position: 'Professional Relations',
        linkedin: 'https://www.linkedin.com/in/bryan-nguyen-38b397276/',
        image: '/officers/Nguyen_Bryan.JPG',
    },
    {
        name: 'Kenneth Wong',
        year: 'Class of 2025',
        major: 'Civil Engineering',
        cohort: 'Spring 2023 Cohort',
        position: 'Finance',
        linkedin: 'https://www.linkedin.com/in/krwong35/',
        image: '/officers/wong_kenneth.jpeg',
    },
    {
        name: 'Jonathan Wu',
        year: 'Class of 2026',
        major: 'Electrical Engineering',
        cohort: 'Fall 2023 Cohort',
        position: 'Finance',
        linkedin: 'https://www.linkedin.com/in/jonathan-wu-link/',
        image: '/officers/wu_jonathan.jpeg',
    },
    {
        name: 'Charlie Edwards',
        year: 'Class of 2026',
        major: 'Computer Science',
        cohort: 'Fall 2023 Cohort',
        position: 'Marketing',
        linkedin: 'https://www.linkedin.com/in/charles-edwards-7540a12a7/',
        image: '/officers/edwards_charlie.jpeg',
    },
    {
        name: 'Fabrizio Lazo Gutierrez',
        year: 'Class of 2026',
        major: 'Mechanical Engineering',
        cohort: 'Fall 2023 Cohort',
        position: 'Marketing',
        linkedin: 'https://www.linkedin.com/in/fabriziolazo3/',
        image: '/officers/Guiterrez_Fabrizio.jpg',
    },
    {
        name: 'Ian Marwong',
        year: 'Class of 2027',
        major: 'Computer Engineering',
        cohort: 'Fall 2023 Cohort',
        position: 'Vice President',
        linkedin: 'https://www.linkedin.com/in/fabriziolazo3/',
        image: '/officers/Marwong_Ian.jpeg',
    },
    {
        name: 'Aliya Abla',
        year: 'Class of 2025',
        major: 'Biomedical Engineering',
        cohort: 'Fall 2023 Cohort',
        position: 'Professional Relations',
        linkedin: 'https://www.linkedin.com/in/aliya-abla/',
        image: '/officers/Abla_Aliya.png',
    },
    {
        name: 'Adrian Chan',
        year: 'Class of 2026',
        major: 'Mechanical and Aerospace Engineering',
        cohort: 'Fall 2023 Cohort',
        position: 'Professional Relations',
        linkedin: 'https://www.linkedin.com/in/adriansc004/',
        image: '/officers/Chan_Adrian.jpg',
    },
    {
        name: 'Shruti Kakar',
        year: 'Class of 2025',
        major: 'Computer Science',
        cohort: 'Fall 2023 Cohort',
        position: 'Vice President',
        linkedin: 'https://www.linkedin.com/in/kakarshruti/',
        image: '/officers/Kakar_Shruti.jpg',
    },
    {
        name: 'Nicholas Xu',
        year: 'Class of 2025',
        major: 'Electrical and Computer Engineering',
        cohort: 'Fall 2023 Cohort',
        position: 'Program Manager',
        linkedin: 'https://www.linkedin.com/in/nicholasxu2026/',
        image: '/officers/Xu_Nicholas.JPG',
    },
    {
        name: 'Seshnag Regoti',
        year: 'Class of 2025',
        major: 'Food Science and Technology',
        cohort: 'Fall 2023 Cohort',
        position: 'Program Manager',
        linkedin: 'https://www.linkedin.com/in/seshnag-regoti/',
        image: '/officers/Regoti_Seshnag.jpg',
    },
    {
        name: 'Alexander Ilusorio',
        year: 'Class of 2025',
        major: 'Electrical Engineering',
        cohort: 'Fall 2023 Cohort',
        position: 'Finance',
        linkedin: 'https://www.linkedin.com/in/alexander-ilusorio-955819296/',
        image: '/officers/Ilusorio_Alexander.png',
    },
    {
        name: 'Kayla Hom',
        year: 'Class of 2024',
        major: 'Computer Science',
        cohort: 'Fall 2023 Cohort',
        position: 'Finance',
        linkedin: 'https://www.linkedin.com/in/kayla-hom/',
        image: '/officers/Hom_Kayla.jpg',
    },
    {
        name: 'Michelle Huo',
        year: 'Class of 2026',
        major: 'Mechanical Engineering',
        cohort: 'Fall 2023 Cohort',
        position: 'Marketing',
        linkedin: 'https://www.linkedin.com/in/michelle-huo-667b80273/',
        image: '/officers/Huo_Michelle.jpg',
    },
    {
        name: 'Vanessa Guo',
        year: 'Class of 2025',
        major: 'Computer Science',
        cohort: 'Fall 2023 Cohort',
        position: 'Finance',
        linkedin: 'https://www.linkedin.com/in/vanessaguo03/',
        image: '/officers/Guo_Vanessa.jpg',
    },
    {
        name: 'Esha Chakrabarty',
        year: 'Class of 2025',
        major: 'Data Science',
        cohort: 'Fall 2023 Cohort',
        position: 'Finance',
        linkedin: 'https://www.linkedin.com/in/esha-chakrabarty/',
        image: '/officers/Chakrabarty_Esha.jpg',
    },
    {
        name: 'Shana Chen',
        year: 'Class of 2026',
        major: 'Systems and Synthetic Biology',
        cohort: 'Fall 2023 Cohort',
        position: 'Finance',
        linkedin: 'https://www.linkedin.com/in/shana-chen-7b853627b/',
        image: '/officers/Chen_Shana.jpg',
    },
    {
        name: 'Nick Lin',
        year: 'Class of 2027',
        major: 'Biomedical Engineering and Music',
        cohort: 'Spring 2024 Cohort',
        position: 'Professional Relations',
        linkedin: 'https://www.linkedin.com/in/nsclin/',
        image: '/officers/Lin_Nick.jpg',
    },
    {
        name: 'Jaclyn Lee',
        year: 'Class of 2026',
        major: 'Biological Systems Engineering',
        cohort: 'Spring 2024 Cohort',
        position: 'Professional Relations',
        linkedin: 'https://www.linkedin.com/in/jaclyn-lee127/',
        image: '/officers/Lee_Jaclyn.jpg',
    },
    {
        name: 'Nicholas Kim',
        year: 'Class of 2026',
        major: 'Mechanical Engineering',
        cohort: 'Spring 2024 Cohort',
        position: 'Professional Relations',
        linkedin: 'https://www.linkedin.com/in/nickim04/',
        image: '/officers/Kim_Nicholas.jpg',
    },
    {
        name: 'Cody Chen',
        year: 'Class of 2027',
        major: 'Computer Science & Engineering',
        cohort: 'Spring 2024 Cohort',
        position: 'Professional Relations',
        linkedin: 'https://www.linkedin.com/in/cody-chen-59701a290/',
        image: '/officers/Chen_Cody.jpeg',
    },
    {
        name: 'Hadi Beveridge Eguino',
        year: 'Class of 2025',
        major: 'Civil Engineering',
        cohort: 'Spring 2024 Cohort',
        position: 'Professional Relations',
        linkedin: 'https://www.linkedin.com/in/hadi-beveridge-eguino/',
        image: '/officers/Eguino_Hadi.JPG',
    },
    {
        name: 'Sumain Chiv',
        year: 'Class of 2026',
        major: 'Mechanical Engineering',
        cohort: 'Spring 2024 Cohort',
        position: 'Professional Relations',
        linkedin: 'https://www.linkedin.com/in/sumain-chiv/',
        image: '/officers/chiv_sumain.jpeg',
    },
    {
        name: 'Colin Chu',
        year: 'Class of 2027',
        major: 'Computer Science and Technology Management',
        cohort: 'Spring 2024 Cohort',
        position: 'Professional Relations',
        linkedin: 'https://www.linkedin.com/in/colinchu27/',
        image: '/officers/Chu_Colin.jpeg',
    },
    {
        name: 'Etienne Rousseau',
        year: 'Class of 2026',
        major: 'Computer Science',
        cohort: 'Spring 2024 Cohort',
        position: 'Professional Relations',
        linkedin: 'https://www.linkedin.com/in/etienne-rousseau/',
        image: '/officers/Rousseau_Etienne.jpg',
    },
    {
        name: 'Lucas Fedronic',
        year: 'Class of 2027',
        major: 'Computer Science and Mathematics',
        cohort: 'Spring 2024 Cohort',
        position: 'Professional Relations',
        linkedin: 'https://www.linkedin.com/in/lucas-fedronic-4b030b217/',
        image: '/officers/Fedronic_Lucas.jpg',
    },
    {
        name: 'Richard Huang',
        year: 'Class of 2025',
        major: 'Computer Science and Engineering',
        cohort: 'Spring 2024 Cohort',
        position: 'Professional Relations',
        linkedin: 'https://www.linkedin.com/in/ridhuang/',
        image: '/officers/Huang_Richard.jpeg',
    },
    {
        name: 'Cindy Shing',
        year: 'Class of 2027',
        major: 'Computer Science',
        cohort: 'Spring 2024 Cohort',
        position: 'Program Manager',
        linkedin: 'https://www.linkedin.com/in/cindy-shing-09387a304/',
        image: '/officers/Shing_Cindy.jpg',
    },
    {
        name: 'Erika Gosti',
        year: 'Class of 2027',
        major: 'Computer Science',
        cohort: 'Spring 2024 Cohort',
        position: 'Professional Relations',
        linkedin: 'https://www.linkedin.com/in/erika-gosti/',
        image: '/officers/Gosti_Erika.JPG',
    },
    {
        name: 'Braeden Wagner',
        year: 'Class of 2025',
        major: 'Electrical Engineering',
        cohort: 'Spring 2024 Cohort',
        position: 'Professional Relations',
        linkedin: 'https://www.linkedin.com/in/braedenwagner/',
        image: '/officers/Wagner_Braeden.jpg',
    },
    {
        name: 'Cecelia Lee',
        year: 'Class of 2024',
        major: 'Mechanical Engineering',
        cohort: 'Spring 2024 Cohort',
        position: 'Professional Relations',
        linkedin: 'https://www.linkedin.com/in/cecilialeeucsd/',
        image: '/officers/Lee_Cecelia.jpg',
    },
    {
        name: 'Oscar Wang',
        year: 'Class of 2025',
        major: 'Computer Science',
        cohort: 'Spring 2024 Cohort',
        position: 'Professional Relations',
        linkedin: 'https://www.linkedin.com/in/wang-oscar/',
        image: '/officers/Wang_Oscar.jpg',
    },
    {
        name: 'Christopher Ordaz',
        year: 'Class of 2026',
        major: 'Electrical Engineering',
        cohort: 'Spring 2024 Cohort',
        position: 'Professional Relations',
        linkedin: 'https://www.linkedin.com/in/christopher-ordaz-44865429a/',
        image: '/officers/Ordaz_Christopher.jpg',
    },
    {
        name: 'Simone Robson',
        year: 'Class of 2025',
        major: 'Environmental Engineering',
        cohort: 'Spring 2024 Cohort',
        position: 'Professional Relations',
        linkedin: 'https://www.linkedin.com/in/simone-robson1/',
        image: '/officers/Robson_Simone.jpeg',
    },

    {
        name: 'Paige Phung',
        year: 'Class of 2027',
        major: 'Aerospace and Mechanical Engineering',
        cohort: 'Fall 2024 Cohort',
        position: 'Professional Relations',
        linkedin: 'https://www.linkedin.com/in/paige-phung/',
        image: '/officers/Phung_Paige.jpeg',
    },
    {
        name: 'Ariba Arif',
        year: 'Class of 2026',
        major: 'Civil Engineering',
        cohort: 'Fall 2024 Cohort',
        position: 'Professional Relations',
        linkedin: 'https://www.linkedin.com/in/ariba-arif-92315a32a/',
        image: '/officers/Arif_Ariba.jpeg',
    },
    {
        name: 'Benjamin Busche',
        year: 'Class of 2026',
        major: 'mechanical Engineering',
        cohort: 'Fall 2024 Cohort',
        position: 'Program Manager',
        linkedin: 'https://www.linkedin.com/in/ben-busche/',
        image: '/officers/Busche_Ben.jpg',
    },
    {
        name: 'Maya Chou',
        year: 'Class of 2027',
        major: 'Electrical Engineering',
        cohort: 'Fall 2024 Cohort',
        position: 'Professional Relations',
        linkedin: 'https://www.linkedin.com/in/maya-chou-350754290/',
        image: '/officers/chou_maya.jpeg',
    },
    {
        name: 'Hieu-Minh To',
        year: 'Class of 2027',
        major: 'Computer Engineering and Economics',
        cohort: 'Fall 2024 Cohort',
        position: 'Professional Relations',
        linkedin: 'https://www.linkedin.com/in/tovuhieuminh/',
        image: '/officers/To_HieuMinh.jpg',
    },
    {
        name: 'Naomi Petersen',
        year: 'Class of 2027',
        major: 'Design',
        cohort: 'Fall 2024 Cohort',
        position: 'Professional Relations',
        linkedin: 'https://www.linkedin.com/in/naomipetersen-/',
        image: '/officers/petersen_naomi.JPEG',
    },
    {
        name: 'Sanjith Iype',
        year: 'Class of 2027',
        major: 'Computer Science and Engineering',
        cohort: 'Fall 2024 Cohort',
        position: 'PrRelationsofessional ',
        linkedin: 'https://www.linkedin.com/in/sanjithiype/',
        image: '/officers/Iype_Sanjith.jpeg',
    },
    {
        name: 'Austin Sidhu',
        year: 'Class of 2027',
        major: 'Computer Engineering',
        cohort: 'Fall 2024 Cohort',
        position: 'Professional Relations',
        linkedin: 'https://www.linkedin.com/in/kanvar-austin-sidhu/',
        image: '/officers/sidhu_austin.jpeg',
    },
    {
        name: 'Nina Dao',
        year: 'Class of 2028',
        major: 'Mechanical Engineering',
        cohort: 'Fall 2024 Cohort',
        position: 'Professional Relations',
        linkedin: 'https://www.linkedin.com/in/nina-dao-98a034272/',
        image: '/officers/dao_nina.jpeg',
    },
    {
        name: 'Marvin Vasquez',
        year: 'Class of 2025',
        major: 'Biosystems Engineering',
        cohort: 'Fall 2024 Cohort',
        position: 'Professional Relations',
        linkedin: 'https://www.linkedin.com/in/marvinedilsarvasquez/',
        image: '/officers/vasquez_marvin.jpeg',
    },
    {
        name: 'Jiya Patel',
        year: 'Class of 2028',
        major: 'Aerospace Engineering',
        cohort: 'Fall 2024 Cohort',
        position: 'Professional Relations',
        linkedin: 'https://www.linkedin.com/in/jiya-patel076/',
        image: '/officers/patel_jiya.jpeg',
    },
    {
        name: 'Desiree Poon',
        year: 'Class of 2028',
        major: 'Biomedical Engineering',
        cohort: 'Fall 2024 Cohort',
        position: 'Professional Relations',
        linkedin: 'https://www.linkedin.com/in/desiree-poon/',
        image: '/officers/Poon_Desiree.jpg',
    },
    {
        name: 'Lorenzo Nakata',
        year: 'Class of 2027',
        major: 'Electrical Engineering',
        cohort: 'Fall 2024 Cohort',
        position: 'Professional Relations',
        linkedin: 'https://www.linkedin.com/in/lorenzo-nakata/',
        image: '/officers/nakata_lorenzo.jpeg',
    },
    {
        name: 'Vincent Ng',
        year: 'Class of 2027',
        major: 'Computer Science and Technology Management',
        cohort: 'Spring 2025 Cohort',
        position: 'Finance',
        linkedin: 'https://www.linkedin.com/in/wang-ng/',
        image: '/officers/Ng_Wang.jpeg',
    },
    {
        name: 'Jeshurun Liou',
        year: 'Class of 2027',
        major: 'Mechanical Engineering',
        cohort: 'Spring 2025 Cohort',
        position: 'Secretary',
        linkedin: 'https://www.linkedin.com/in/jeshurunliou/',
        image: '/officers/Liou_JJ.jpeg',
    },
    {
        name: 'Angie Li',
        year: 'Class of 2028',
        major: 'Civil Engineering',
        cohort: 'Spring 2025 Cohort',
        position: 'Professional Relations',
        linkedin: 'https://www.linkedin.com/in/angiezhixinli/',
        image: '/officers/li_angie.jpeg',
    },
    {
        name: 'John Macaranas',
        year: 'Class of 2027',
        major: 'Electrical Engineering',
        cohort: 'Spring 2025 Cohort',
        position: 'Finance',
        linkedin: 'https://www.linkedin.com/in/john-elrenz-macaranas/',
        image: '/officers/macaranas_john.jpg',
    },
    {
        name: 'Saatvik Subramaniam',
        year: 'Class of 2027',
        major: 'Electrical Engineering',
        cohort: 'Spring 2025 Cohort',
        position: 'Marketing',
        linkedin: 'https://www.linkedin.com/in/saatvik-subramaniam/',
        image: '/officers/subramaniam_saatvik.jpg',
    },
    {
        name: 'Jefferson Fan',
        year: 'Class of 2027',
        major: 'Mechanical Engineering',
        cohort: 'Spring 2025 Cohort',
        position: 'Finance',
        linkedin: 'https://www.linkedin.com/in/jeffersonfan/',
        image: '/officers/fan_jefferson.jpg',
    },
    {
        name: 'Sakura Chiwata',
        year: 'Class of 2028',
        major: 'Mechanical Engineering',
        cohort: 'Spring 2025 Cohort',
        position: 'Finance',
        linkedin: 'https://www.linkedin.com/in/sakurachiwata/',
        image: '/officers/chiwata_sakura.jpeg',
    },
    {
        name: 'Arnav Akula',
        year: 'Class of 2026',
        major: 'Computer Science and Statistics',
        cohort: 'Spring 2025 Cohort',
        position: 'Finance',
        linkedin: 'https://www.linkedin.com/in/arnavakula/',
        image: '/officers/akula_arnav.jpg',
    },
    {
        name: 'Andrew Harrington',
        year: 'Class of 2027',
        major: 'Civil Engineering',
        cohort: 'Spring 2025 Cohort',
        position: 'Marketing',
        linkedin: 'https://www.linkedin.com/in/andrewdharrington/',
        image: '/officers/harrington_andrew.jpeg',
    },
    {
        name: 'Kaitlyn Hahn',
        year: 'Class of 2027',
        major: 'Computer Science',
        cohort: 'Spring 2025 Cohort',
        position: 'Marketing',
        linkedin: 'https://www.linkedin.com/in/kaitlyn-hahn/',
        image: '/officers/hahn kaitlyn.JPG',
    },
    {
        name: 'Joshua Wei',
        year: 'Class of 2027',
        major: 'Data Science and Neuroscience',
        cohort: 'Spring 2025 Cohort',
        position: 'Marketing',
        linkedin: 'https://www.linkedin.com/in/joshuaweiiii/',
        image: '/officers/wei_joshua.jpg',
    },
    {
        name: 'Ryan Nguyen',
        year: 'Class of 2027',
        major: 'Electrical Engineering',
        cohort: 'Spring 2025 Cohort',
        position: 'Career Development',
        linkedin: 'https://www.linkedin.com/in/ryan-nguyen-davis/',
        image: '/officers/nguyen_ryan.jpeg',
    },
    {
        name: 'Lianne R. De Leon',
        year: 'Class of 2027',
        major: 'Mechanical Engineering',
        cohort: 'Spring 2025 Cohort',
        position: 'Internal Affairs',
        linkedin: 'https://www.linkedin.com/in/liannerdl/',
        image: '/officers/Leon_Lianne.jpg',
    },
    {
        name: 'Hanna Dao',
        year: 'Class of 2028',
        major: 'Mechanical Engineering',
        cohort: 'Spring 2025 Cohort',
        position: 'Internal Affairs',
        linkedin: 'https://www.linkedin.com/in/hannadao/',
        image: '/officers/dao_hanna.jpg',
    },
    {
        name: 'Hishaan Rajwani',
        year: 'Class of 2028',
        major: 'Computer Science and Engineering',
        cohort: 'Spring 2025 Cohort',
        position: 'Internal Affairs',
        linkedin: 'https://www.linkedin.com/in/hishaanrajwani/',
        image: '/officers/rajwani_hishaan.jpeg',
    },
    {
        name: 'Gavin Pasillas',
        year: 'Class of 2027',
        major: 'Chemical Engineering',
        cohort: 'Spring 2025 Cohort',
        position: 'Professional Relations',
        linkedin: 'https://www.linkedin.com/in/gavinpas/',
        image: '/officers/pasillas_gavin.jpeg',
    },
    {
        name: 'Michelle Lin',
        year: 'Class of 2027',
        major: 'Data Science',
        cohort: 'Spring 2025 Cohort',
        position: 'Internal Affairs',
        linkedin: 'https://www.linkedin.com/in/michelle-lin-3a441b281/',
        image: '/officers/lin_michelle.jpeg',
    },
    {
        name: 'Jacob Mashini',
        year: 'Class of 2027',
        major: 'Civil and Environmental Engineering',
        cohort: 'Spring 2025 Cohort',
        position: 'Internal Affairs',
        linkedin: 'https://www.linkedin.com/in/jacob-mashini-0105b0295/',
        image: '/officers/mashini_jacob.jpeg',
    },
    {
        name: 'Ryan Nakayama',
        year: 'Class of 2029',
        major: 'Mechanical Engineering',
        cohort: 'Fall 2025 Cohort',
        position: 'Internal Affairs',
        linkedin: 'https://www.linkedin.com/in/ryannakayama/',
        image: '/officers/nak_ryan.jpeg',
    },
    {
        name: 'Atharva Kharwadkar',
        year: 'Class of 2027',
        major: 'Mechanical Engineering',
        cohort: 'Fall 2025 Cohort',
        position: 'Internal Affairs',
        linkedin: 'https://www.linkedin.com/in/atharvakharwadkar/',
        image: '/officers/kharwadkar_atharva.jpeg',
    },
    {
        name: 'Jessica Ting',
        year: 'Class of 2026',
        major: 'Computer Science and Technology Management',
        cohort: 'Fall 2025 Cohort',
        position: 'Internal Affairs',
        linkedin: 'https://www.linkedin.com/in/jessica-ting-404034352/overlay/background-image/',
        image: '/officers/ting_jessica.jpeg',
    },
    {
        name: 'Sachin Venkat',
        year: 'Class of 2028',
        major: 'Computer Science',
        cohort: 'Fall 2025 Cohort',
        position: 'Internal Affairs',
        linkedin: 'https://www.linkedin.com/in/sachinvenkat/',
        image: '/officers/venkat_sachin.jpg',
    },
    {
        name: 'Sophia Palae',
        year: 'Class of 2029',
        major: 'Data Science',
        cohort: 'Fall 2025 Cohort',
        position: 'Internal Affairs',
        linkedin: 'https://www.linkedin.com/in/moe-palae/',
        image: '/officers/Palae_Sophia.jpeg',
    },
    {
        name: 'Benjamin Brundage',
        year: 'Class of 2028',
        major: 'Computer Engineering',
        cohort: 'Fall 2025 Cohort',
        position: 'Internal Affairs',
        linkedin: 'https://www.linkedin.com/in/benjamin-brundage-63319633a/',
        image: '/officers/brundage_ben.jpeg',
    },
    {
        name: 'Ethan Cooc',
        year: 'Class of 2029',
        major: 'Computer Science',
        cohort: 'Fall 2025 Cohort',
        position: 'Internal Affairs',
        linkedin: '',
        image: '/officers/cooc_ethan.jpeg',
    },
    {
        name: 'Claris Tain',
        year: 'Class of 2026',
        major: 'Electrical Engineering',
        cohort: 'Fall 2025 Cohort',
        position: 'Internal Affairs',
        linkedin: 'https://www.linkedin.com/in/claris-tain/',
        image: '/officers/tain_claris.jpeg',
    },
    {
        name: 'Donald Le',
        year: 'Class of 2028',
        major: 'Chemical Engineering',
        cohort: 'Fall 2025 Cohort',
        position: 'Internal Affairs',
        linkedin: 'https://www.linkedin.com/in/donald-l-a46009283/',
        image: '/officers/le_donald.jpeg',
    },
    {
        name: 'Ryan Ton',
        year: 'Class of 2028',
        major: 'Computer Engineering',
        cohort: 'Fall 2025 Cohort',
        position: 'Internal Affairs',
        linkedin: 'https://www.linkedin.com/in/ryan-ton-788970280/',
        image: '/officers/ton_ryan.jpeg',
    },
    {
        name: 'Nik Buerger',
        year: 'Class of 2027',
        major: 'Mechanical Engineering',
        cohort: 'Fall 2025 Cohort',
        position: 'Internal Affairs',
        linkedin: '',
        image: '/officers/Buerger_Nik.jpeg',
    },
    {
        name: 'Maya Athayasay',
        year: 'Class of 2028',
        major: 'Chemical Engineering',
        cohort: 'Fall 2025 Cohort',
        position: 'Internal Affairs',
        linkedin: 'https://www.linkedin.com/in/maya-athayasay/',
        image: '/officers/Athaysay_Maya.jpeg',
    },
    {
        name: 'Adam Kim',
        year: 'Class of 2028',
        major: 'Computer Engineering',
        cohort: 'Fall 2025 Cohort',
        position: 'Internal Affairs',
        linkedin: 'https://www.linkedin.com/in/adam-kim-167957327/',
        image: '/officers/kim_adam.jpeg',
    },
    {
        name: 'Nancy Wang',
        year: 'Class of 2028',
        major: 'Computer Science',
        cohort: 'Fall 2025 Cohort',
        position: 'Internal Affairs',
        linkedin: 'https://www.linkedin.com/in/nancywang22/',
        image: '/officers/wang_nancy.jpeg',
    },
    {
        name: 'Kenneth Nguyen',
        year: 'Class of 2028',
        major: 'Environmental Engineering',
        cohort: 'Fall 2025 Cohort',
        position: 'Internal Affairs',
        linkedin: 'https://www.linkedin.com/in/kenneth-nguyen-b1098b320/',
        image: '/officers/nguyen_kenneth.jpeg',
    },
    {
        name: 'Madeleine Kim',
        year: 'Class of 2029',
        major: 'Biological Systems Engineering',
        cohort: 'Fall 2025 Cohort',
        position: 'Internal Affairs',
        linkedin: 'https://www.linkedin.com/in/madeleine-kim-b7554637a/',
        image: '/officers/kim_madeleine.jpeg',
    },
    {
        name: 'Devin Sidhu',
        year: 'Class of 2028',
        major: 'Statistics',
        cohort: 'Fall 2025 Cohort',
        position: 'Internal Affairs',
        linkedin: 'https://www.linkedin.com/in/devin-gill-sidhu-a03745328/',
        image: '/officers/sidhu_devin.jpeg',
    },
    {
        name: 'Justin Yee',
        year: 'Class of 2026',
        major: 'Data Science',
        cohort: 'Fall 2025 Cohort',
        position: 'Internal Affairs',
        linkedin: 'https://www.linkedin.com/in/jhyee/',
        image: '/officers/yee_justin.png',
    },
    {
        name: 'Ellaina Kimura',
        year: 'Class of 2029',
        major: 'Biomedical Engineering',
        cohort: 'Fall 2025 Cohort',
        position: 'Internal Affairs',
        linkedin: 'https://www.linkedin.com/in/ellaina-kimura-176b74389/',
        image: '/officers/Kimura_Ellaina.jpeg',
    }






    


    
]