export const eboard = [
    {
        name: 'n8 dogg',
        year: 'Class of 2023',
        major: 'Podiatric Medicine and Engineering',
        cohort: 'Fall 2021 Cohort',
        position: 'President',
        linkedin: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
        image: '/officers/n8.jpeg',
    },
    {
        name: 'mamanda',
        year: 'Class of 2023',
        major: 'Podiatric Medicine and Engineering',
        cohort: 'Fall 2021 Cohort',
        position: 'President',
        linkedin: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
        image: '/officers/ama.png',
    },
    {
        name: 'n8 dogg',
        year: 'Class of 2023',
        major: 'Podiatric Medicine and Engineering',
        cohort: 'Fall 2021 Cohort',
        position: 'President',
        linkedin: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
        image: '/officers/n8.jpeg',
    },
    {
        name: 'mamanda',
        year: 'Class of 2023',
        major: 'Podiatric Medicine and Engineering',
        cohort: 'Fall 2021 Cohort',
        position: 'President',
        linkedin: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
        image: '/officers/ama.png',
    },
]